name: Gimasys GitHub Acions Workflow Demo
run-name: Test thử Salesforce Code Analysis scanner khi push code len main
on:
  push:
    branches:
      - main
jobs:
  chay-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Đi tới git repo này
        uses:  actions/checkout@v3
      - name: in ra chao cau
        run: echo "Chào cậu. Cậu tuyệt lắm!"
      - name: Install SFDX CLI và Salesforce Code Analyzer scanner
        run: |
          npm install sfdx-cli --global
          npm install @salesforce/cli --global
          sfdx plugins:install @salesforce/sfdx-scanner
      - name: SFDX Scan Pull Request
        uses: mitchspano/sfdx-scan-pull-request@v0.1.4
        with:
          severity-threshold: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
